/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * Sonic SVM ZkBridge API
 * OpenAPI spec version: 0.0.1
 */

export interface MintOnBridgeDto {
  amount: number;
  dst: string;
  src: string;
  srcTxHash: string;
}
